### PR TITLE
Add -open and -close options

### PR DESCRIPTION
**Pull request by RRRRRm**
Hi, I just added the -open and -close options to make sure that sometimes open and close need to be specified explicitly.

### CODE REVIEW

**Comment by RRRRRm** [comment]
I also add two signals to specify close and open:

SIGUSR2 for open, and SIGRTMIN+3 for close, which is user defined real-time signals.

**Comment by nwg-piotr** [comment]
Could you also describe new flags and signals in README.md?

**Comment by RRRRRm** [comment]
Done!

**Review by nwg-piotr — COMMENTED** [review]
Why "Terminal emulator (default "xterm-kitty")"?

nwg-drawer is a part of the nwg-shell project, where foot is the default terminal emulator.

**Comment by RRRRRm** [comment]
Sorry for the direct copy of `--help`, probably because I used kitty when compiling

main.go:173
```
var term = flag.String("term", defaultTermIfBlank(os.Getenv("TERM"), "foot"), "Terminal emulator")
```

**Review by nwg-piotr — APPROVED** [review]

**Pull request merged**
