### PR TITLE
Add flags to set window margins

### PR DESCRIPTION
**Pull request by snehrbass**

### CODE REVIEW

**Review by nwg-piotr — COMMENTED** [review]
This won't be merged until the ongoing work by @Raffy23 is ready. Please be patient.

**Comment by snehrbass** [comment]
@nwg-piotr Sorry, my intention was to be helpful, not impatient.

**Comment by nwg-piotr** [comment]
Yeah, just wanted to apologize for the possible delay. :)

**Comment by Raffy23** [comment]
@nwg-piotr feel free to merge any PRs you like, if any merge conflicts should happen I will try to resolve them (rebasing my branches) before merging ^^.

**Comment by nwg-piotr** [comment]
Last week I lost some work by merging not rebased branch too hastily. :D

**Comment by nwg-piotr** [comment]
@snehrbass The other branches merged. Could you please rebase yours?

**Comment by snehrbass** [comment]
@nwg-piotr done

**Pull request merged**
