### PR TITLE
use terminal environment variable if present

### PR DESCRIPTION
**Pull request by james-lawrence**
lets the environment choose the terminal automatically.

### CODE REVIEW

**Comment by nwg-piotr** [comment]
Do we still need `xdgdesktop_parser*` files?

**Comment by james-lawrence** [comment]
@nwg-piotr ? i mean you can move the code in them anywhere you want if that is what you are asking.

**Comment by nwg-piotr** [comment]
Well, I got used to testing with `go run *.go`, what's impossible now.

**Comment by james-lawrence** [comment]
its the test file causing the issue. `go run .`does what you want it doesn't explicitly tell it to load everything via the *.go.

**Comment by nwg-piotr** [comment]
Alright, that's not a problem.

**Pull request merged**
