### PR TITLE
update golang lib dependencies

### PR DESCRIPTION
**Pull request by 6543**

### CODE REVIEW

**Comment by 6543** [comment]
@ nwg-piotr do you need something from me, to review my 4 pulls ?

**Comment by 6543** [comment]
@nwg-piotr do you need something from me, to review my 4 pulls ?

**Comment by nwg-piotr** [comment]
No. Just needed to finish what I was working on, and now it's 4am in my place. I'll take care of your PRs in the evening.

**Comment by 6543** [comment]
well thanks :)

*me looking at 6am - I should take sleep*

**Review by nwg-piotr — APPROVED** [review]

**Pull request merged**
