### PR TITLE
add support to hyprlandctl

### PR DESCRIPTION
**Pull request by gouvinb**
# Description

This pull request adds the `wm` flag to the `nwg-drawer` command to launch a program with the `swaymsg exec` or `hyprctl dispatch exec` command. 

## :warning: BREAKING CHANGE: '-swaymsg' removed, use '-wm sway' instead

# Reference

This pull request refers to [this comment (#101)](https://github.com/nwg-piotr/nwg-drawer/pull/101#issuecomment-1793731376)

# Instructions

To use this new feature, simply add the `-wm <current wm name>` argument to the `nwg-drawer` command, or set the `XDG_CURRENT_DESKTOP` environment variable to "sway", "hypr" or "hyprland".

### Before

    rubymine # without -term, -swaymsg and without XDG_CURRENT_DESKTOP=sway

### After

    swaymsg exec firefox # with `-wm sway` or with XDG_CURRENT_DESKTOP=sway

or

    hyprctl dispact exec firefox # with `-wm hyprland` or with XDG_CURRENT_DESKTOP=hyprland

or

    hyprctl dispact exec firefox # with `-wm hypr` or with XDG_CURRENT_DESKTOP=hypr

# Note

I don't use Hypr or Hyprland (yet). So this PR must be tested.

### CODE REVIEW

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
It should be `hyprctl`, hot `hyprlandctl`, e.g.: `hyprctl dispatch exec alacritty`.

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
Seems to work well on Hyprland. Would you mind adding the prefix to the output in https://github.com/gouvinb/nwg-drawer/blob/808fd032a0ffd675b4cf20b221f3f8c9702fe56c/tools.go#L621 ?

**Comment by gouvinb** [comment]
I reworked command building.

Typical shell-supported command sets:

- `cmd`
- `cmd --arg`
- `cmd --arg=value`
- `ENV_VAR="value" cmd`
- `ENV_VAR="value" cmd --arg`
- `ENV_VAR="value" cmd --arg=value`

The listed commands above are now better managed.

Initially, the command types `cmd --arg=value` or `ENV_VAR="value" cmd --arg=value` were not correctly parsed. After finding a solution to this problem, I conducted further tests and discovered cases that were not currently handled. These cases are as follows:

- `cmd "arg with space"`
- `ENV_VAR="value with space" cmd`

**Review by nwg-piotr — CHANGES_REQUESTED** [review]
Running apps with go is insanely complicated and always makes me miss the good, old python. I'm afraid we will never have a code that properly starts everything  with all possible env vars and arguments. 

However:

### main.go, line 128 is ambiguous

`log.Warn("nwg-drawer support only 'swaymsg' or 'hyprland'.")`

Consider something like this:

`log.Warn("-wm argument supports only sway or hyprland string")`

### main.go, line 152, the description is not true

`var wm = flag.String("wm", defaultStringIfBlank(os.Getenv("XDG_CURRENT_DESKTOP"), ""), "Use swaymsg (with 'sway' argument) or hyprctl (with 'hypr' or 'hyprland')")`

We only seem to support the `hyprland` argument, but not `hypr`.

**Comment by gouvinb** [comment]
> Running apps with go is insanely complicated and always makes me miss the good, old python.

The approach with the Go language is a bit too low-level.

I think that most cases are covered and that the remaining 2 cases represent only a minority of situations.

Personally, I've never had a case like this; I had to invent them myself to check whether they worked or not.

**Review by nwg-piotr — APPROVED** [review]

**Comment by nwg-piotr** [comment]
All right. Let's find it ready.

**Pull request merged**
