### PR TITLE
smal code refactors

### PR DESCRIPTION
**Pull request by 6543**
just some smal code refactorings while looking at the code

### CODE REVIEW

**Review by nwg-piotr — APPROVED** [review]

**Comment by 6543** [comment]
@nwg-piotr thanks - hope it helped :)

**Comment by nwg-piotr** [comment]
Thank you.

Do you by aby chance use nwg-shell as a whole? For quite a long time I've been looking for a contributor willing to become  a project collaborator. I mean someone who not only cares of their own issues/ideas, but would also help at resolving users' issues. Are you interested?

**Comment by 6543** [comment]
hey well first I'm currently transitioning to hyperland.

for now I'll use the nwg-display and nwg-drawer, ...

... I can also from time to time review stuff If you want and if my transitioning is finished, I'll daily drive them so I might also submit some more pulls ...

but to consider me as a full-dedicated collaborator well ... I already have some very big project's that I'm one of the leading devs ...

If you do not have a chat-space for the nwg project ... I suggest you start with a matrix-space and people will come?

**Comment by nwg-piotr** [comment]
OK, I need a seasoned nwg-shell user, both on sway and Hyprland.

> I suggest you start with a matrix-space and people will come?

I'm afraid not. I had not enough patience to browse matrix, as it's slow as a pregnant snail. And actually nobody uses it. I decides to stick to GitHub Discussions, Reddit and Mastodon for now.

**Comment by 6543** [comment]
they all are fine but do not allow chat-style conversation as we do here (by abusing the issue comments)

if matrix isn't something for you ... discord is also well established in the opensource-dev world ... but it's proprietary

**Comment by 6543** [comment]
ps my mastodon: https://chaos.social/@6543

**Comment by nwg-piotr** [comment]
I keep an eye out on two Discord servers: ArchLabs & Friends (former ArchLabs Linux forum people), and Hypr Development. While the first is quite ordered, the second one is overwhelming to me, and I have no patience to read it. Generally I don't like Discord at all.

Being a developer, graphics designer and social media manager is impossible for one person in the long run. That's why I'm looking for a team, so far unsuccessfully.

**Comment by 6543** [comment]
I'll come back to you If I think I might dedicate more to this :)

If that's ok

**Comment by 6543** [comment]
And if you struggle with something, just ping me

**Comment by nwg-piotr** [comment]
Of course. Thanks for your contribution.

**Pull request merged**
